spring.application.name=compliance

spring.datasource.url=jdbc:postgresql://190.123.34.157:5432/DB_Alta_compliance
spring.datasource.username=postgres
spring.datasource.password=dba
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true